#---
# Author: Marcos Antonio de Carvalho (maio/2023)
# Descr.: Construção da infraestrutura Event-Driven-Stack 
#         Construida em containers Docker:
#         - rabbitmq
#         - flower
#         - postman (Python - FastAPI e Celery)
#         - celery  (Python - Celery)
#---

version: "3.7"

##------------##     
##  Networks  ##
##------------##
networks:
  backend: # Rede do backend stack

##------------##     
##  Services  ##
##------------##
services:

  rabbitmq:
    # http://localhost:15692/metrics
    build: 
      context: .
      dockerfile: dockerfiles/rabbitmq/Dockerfile
    image: owl-arch/rabbitmq:events-driven-stack
    container_name: 'message-broker'
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes: 
      - ./mount/rabbitmq/data/:/var/lib/rabbitmq/
      - ./mount/rabbitmq/log/:/var/log/
      - ./mount/rabbitmq/config:/etc/rabbitmq/rabbitmq.conf
    deploy:
      mode: global      
    networks:
      backend:

  flower:
    build: 
      context: .
      dockerfile: dockerfiles/flower/Dockerfile
    entrypoint: celery
    command: flower
    container_name: 'monitor-online'
    hostname: flower
    image: owl-arch/flower:events-driven-stack
    environment:
      # https://github.com/sirodoht/opencult.com/issues/43
      # Atenção para não colocar " nessas variáveis
      - CELERY_BROKER_URL=amqp://owl:owl@rabbitmq
      - FLOWER_PORT=5566
    user: user  # Restrição de acesso (nobody não funciona no flower)
    ports:
      - 5566:5566
    depends_on:
      - rabbitmq 
    deploy:
      mode: global      
    networks:
      backend:

  webapi:
    build: 
      context: .
      dockerfile: dockerfiles/webapi/Dockerfile
    image: owl-arch/webapi:events-driven-stack
    container_name: 'task-producer-webapi'
    hostname: postman
    entrypoint: python
    command: ./WebAPI.py  
    environment:
      - BROKER_URL=amqp://rabbitmq:5672
      - RESULT_BACKEND=rpc://
    # user: nobody # Restrição de acesso 
    ports:
      - 8000:8000      
    depends_on:
      - rabbitmq 
    deploy:
      mode: global      
    networks:
      backend:

  celery:
    build: 
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    container_name: 'task-consumer-worker'
   #image: celery:services_domain
   #hostname: A
    image: owl-arch/celery:events-driven-stack
    hostname: '{{.Node.ID}}'
    #env_file: dockerfiles/celery/.env
    environment:
      - BROKER_URL=amqp://owl:owl@rabbitmq:5672
      - RESULT_BACKEND=rpc://
      - C_FORCE_ROOT=true
    #volumes: 
    #  - ./mount/celery/log/:/home/celery/log/
    depends_on:
      - rabbitmq 
    #deploy:
    #  replicas: 3 # replicas worker que serão criados
    networks:
      backend:

